name: Maven App Versioning

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version Type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - none
jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Handle Version Type (Only for workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.version_type }}" = "none" ]; then
            echo "Skipping version bump and Docker image promotion."
            exit 0
          fi

      - name: Choose version up for maven
        run: |
          case "${{ github.event.inputs.version_type }}" in
            major) mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.nextMajorVersion}.0.0' versions:commit ;;
            minor) mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0' versions:commit ;;
            patch) mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}' versions:commit ;;
          esac
      - name: Extract Version from Maven
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          echo "docker build -t mycustom.registry/myapp:${{ env.VERSION }} . "
          echo " docker push mycustom.registry/myapp:${{ env.VERSION }}"

      - name: Set up Git Authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Push new version to github
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "chore: bump version to ${{ env.VERSION }}"
          git push
          
      - name: Tag and Push Version
        run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
